### ISSUE TITLE
Are reports supposed to be accessible? 

### ISSUE THREAD

**Issue by vladdoster** [singularityhub/stools#7]
I need some clarification.

Do I understand the code correctly?

1. You run `sclair` on an image (.sif file)
2. It gets scanned and generates a report
3. Reports are put in /var/www/images
4. You can browse reports at host:8080/images?

Or is the webserver for something else? It seems the server process gets killed after each run.

**Comment by vsoch** [comment]
clair _is_ a server (service), so when you generate a report it's moreso doing:

 - [starting the server](https://github.com/singularityhub/stools/blob/master/stools/clair/__init__.py#L110) on the port speciied
 - [exporting a singularity sif](https://github.com/singularityhub/stools/blob/master/stools/clair/__init__.py#L127) to .tar.gz archives so they can be scanned akin to docker layers
 - [generating the report](https://github.com/singularityhub/stools/blob/master/stools/clair/__init__.py#L144) and printing to stdout

So the /var/www/images is not for reports, it's for layers. The port exposes the clair API (I don't recall what you'd see if you browsed there). If you wanted to have an option to save reports somewhere, this would be relatively easy to do - let me know if you'd like to talk about adding this feature and we can develop it!

**Comment by acullenn** [comment]
I'll take a crack at adding that feature. Doesn't seem too difficult at first glance. I'll write it up and send a PR when it's ready for review!

**Comment by vsoch** [comment]
Awesome! [Here is the report function](https://github.com/singularityhub/stools/blob/master/stools/clair/api.py#L57) and you can see it already returns json, so I think the main decisions that we would need to think about would be:

### how to have the client ask to save images?
Would it make sense to add a `--report` flag that would accept a folder to save to (and then save based on the container name that is originally parsed) and by default, we don't save, since a user might just want to run it one-off and print to the screen?

### where to save images?
Given some folder, we could easily tell the user to create a subfolder in /code (which is bound to the pwd)

```bash
mkdir -p reports
```

And then the current setting would already work!

```yaml
  volumes:
    - .:/code
```

And then tell the tool to save the reports there:
```bash
docker exec -it clair-scanner sclair test/container.sif --reports /code/reports
```
Looking forward to seeing!

**Comment by acullenn** [comment]
Yeah I was definitely thinking of adding a --report flag to parser.

I think not saving by default is realistic, and since /code is bound already I think that the /code/reports directory makes perfect sense. 

I do like flexibility though, so I'm of the mind to make the --report flag and have it accept a path as an argument. Then in the reporting section, have some logic so if an additional argument isn't passed it defaults to /code/reports (making that directory if it doesn't exist already). 

Does that sound reasonable?

**Comment by vsoch** [comment]
Yes, that is on point with my suggestion, so +1 from me! The only tweak I'd say is that we should not be in the business of creating directories for the user - so require reports to exist. What we can do is commit an example report to a reports folder in the repo, so it already will. What we don't want to happen is for a user to set a different /custom path (but have some mistake) and then have it created anyway.

**Comment by acullenn** [comment]
> What we can do is commit an example report to a reports folder in the repo, so it already will.

Can you clarify this a little for me? I'm not super familiar on the process that goes on from repo -> built container

**Comment by vsoch** [comment]
The user is told to run the docker-compose file from the repository here, it's this one:

https://github.com/singularityhub/stools/blob/master/docker-compose.yml

In that file, we mount the present working directory (the root of the repo) to /code in the container.

```yaml
  volumes:
    - .:/code
```
This means that if we have a folder, reports, in the repository, it will be mounted at /code/reports. You can't add an empty folder to a GitHub repo, so if (during development) we generate an example report.json (likely named based on the container URI it's from) then it will be present. There isn't any process beyond:

1. we build the container with code from the repo root
2. but then we bind the root to /code anyway
3. so then whatever is in the root is in /code in the container, and persists to the host (like the reports)

Is that more clear?

**Comment by acullenn** [comment]
Perfectly, thank you for that! The docker-compose piece is what I was missing.

I'll whip up a report with ubuntu:latest and that can be our example.

**Comment by vsoch** [comment]
Thank you @acullenhms and @vladdoster ! We've just merged your changes. I'm going to add black now (I am quite a fan too!)
